# Generated by Django 2.2.16 on 2020-10-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_hjh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kjfkfhd', models.BigIntegerField()),
            ],
        ),
    ]
